# Generated by Django 4.2.1 on 2023-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
